### ISSUE TITLE
Filtering blog posts after switching category

### ISSUE THREAD

**Issue by s-gbz** [codeklasse/codeklasse.de#30]
Filtering blog posts while a category is selected, makes the mechanisms filter _inside_ the selected category.
However, it is expected so search in _all_ of the posts.
This happens _after_ the search field is reset and thus all posts are reset as well.

https://user-images.githubusercontent.com/23424538/148444064-eebb5553-b435-45d2-9386-0b420dd668dc.mp4

**Comment by s-gbz** [comment]
Further demonstration

https://user-images.githubusercontent.com/23424538/151827075-25777aa9-f337-44b4-bf7d-a537d3053093.mp4

**Comment by seann1** [comment]
I will complete this issue. Feel free to assign it to me
