### ISSUE TITLE
Contact forms should require valid input

### ISSUE THREAD

**Issue by s-gbz** [codeklasse/codeklasse.de#33]
As of right now, forms can be send in without any entries.
Add a requirement to enter a name, message & valid email.

**Comment by s-gbz** [comment]
(Not technically a bug, but undesired behaviour nonetheless.

**Comment by pramod74** [comment]
Hi @s-gbz,

I would like to work on this issue. Please let me know the form(s) where these checks need to be added.
Also, kindly assign the issue to me.

Thanks,
Pramod

**Comment by s-gbz** [comment]
Hey there @pramod74 - thanks for your kind suggestion!
Just to lift some confusion though - how did you stumble upon this issue?
I'd be more than curious to know!

In case you want to take a look at the form, it's right [here <-](https://github.com/codeklasse/codeklasse.de/blob/master/_includes/contact-form.html).

**Comment by pramod74** [comment]
Hi @s-gbz,

Thanks for pointing me to the form. I have added checks to ensure that the user enters some value in each of the three fields before the form can be submitted. By default, email address would accept an input only if it includes '@' character. Kindly review PR (# 37) submitted by me. If you would like to implement additional validations on any of these fields, please let me know.

I stumbled upon this issue on www.goodfirstissues.com. It seems as if they are maintaining a list of issues suitable to be taken up by first time contributors.

Thanks,
Pramod

**Comment by s-gbz** [comment]
This is amazing! Thanks a lot for your kind contribution @pramod74 !
I'll merge this first issue just to wrap it up, however it would be awesome if we could have a _personalized_ error message if some of the fields were left open.
I'll create a new issue now (#39) - feel free to grab it you like (and thanks again, this was unexpected :slightly_smiling_face: )

**Comment by pramod74** [comment]
My pleasure, @s-gbz. Thanks for your encouraging remarks.

I would like to work on the new issue (# 39) too. However, I am relatively a newbie, and it may take me some time to submit a PR. If it is not really urgent to be fixed, kindly assign it to me.

Thanks,
Pramod
