### ISSUE TITLE
Evaluate backward compatibility and add ruby gem "webrick"

### ISSUE THREAD

**Issue by s-gbz** [codeklasse/codeklasse.de#45]
Ruby versions less than 3.0 appear to work just fine with out configuration.
However, more recent versions seem to require "webrick" to function.

Task: Check build compatibility with said gem & add it to setup. 

See 
- https://github.com/github/pages-gem/issues/752
- https://github.com/jekyll/jekyll/issues/8523

**Comment by liam-k** [comment]
The gem itself isn’t the problem, just Jekyll’s incompatibility with Ruby >= 3.0. See my PR #46 – simple fix.
