### ISSUE TITLE
Introduce a consistent button design

### ISSUE THREAD

**Issue by liam-k** [codeklasse/codeklasse.de#54]
Buttons on our site are inconsistently designed. 
While buttons on the landing page are yellow and white. On hover, their background color doesn’t change, but the border color changes to a mint green (which I doesn’t really fit the rest of the styling in my opinion).

<img width="325" alt="image" src="https://user-images.githubusercontent.com/34057943/153030460-085392c5-9c7f-4c18-b6dc-b0a9e36b45cd.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/34057943/153030435-b342e302-dbb0-496a-b0fc-18e684e78c72.png">

Buttons on the [blog](https://codeklasse.de/blog/) page have a green text color and in their hover & active states, their color changes to a lighter and darker green respectively. Also, borders are removed on hover. 

All buttons should have a consistent design. I played around a bit and for the landing page, I like this behavior: 

https://user-images.githubusercontent.com/34057943/153028074-6519b776-b7fb-4241-b9b7-b8cabb7cab72.mov

CSS for the hover state: 
```
border-color: #000;
transition: ease-in-out 0.2s;
box-shadow: 4px 4px;
```
(Transition needs to be applied to the default state as well of course.)

Easy enough – however, we still need a solution for the blog categories which also need an active state so we can see the selected category (also, they shouldn’t be green anymore). A very light & subtle shade of grey as background color might work. 

An alternative approach would be to grow the buttons to about 120% or something on hover, and then add the shadow or a darker background color for the active state.

**Comment by s-gbz** [comment]
Actually, let's introduce a constant shadow and remove it on :hover, similiar to pressing a button
(See here: https://justsketch.me/)

https://user-images.githubusercontent.com/23424538/172122191-8decc5d7-8f16-427f-86a7-a3967005cd3f.mp4

**Comment by liam-k** [comment]
You’re right, makes more sense. I really like the design Sophia used in her styleguide. Looks very ✨ 3 D ✨ because the shadow has this kinda trapezoid shape.  Might be a bit tricky in CSS though. 


<img width="928" alt="image" src="https://user-images.githubusercontent.com/34057943/172210756-881e8d42-88c3-4c1c-9841-310e3a85da7f.png">

**Comment by s-gbz** [comment]
Done! However, I will ignore the trapezoid shape for now.
It's a minor detail and just fine the way it's now.
