### ISSUE TITLE
Reshape "why-use-codeklasse" & FAQ section on front page

### ISSUE THREAD

**Issue by liam-k** [codeklasse/codeklasse.de#57]
Font size in explanation boxes & FAQs should be larger so it’s easier to read. Maybe we can also increase font size for the subheadings.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/34057943/153032813-78befe77-68e3-40a1-b705-1f6e76237672.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/34057943/153033616-7548b111-d1f3-4936-b88e-6795044de8ed.png">

Subheadings:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/34057943/153033660-b8a5c3a8-e9bb-48d7-822f-721e99da66bb.png">

Also see #56.

**Comment by s-gbz** [comment]
I think it'd be worthwhile appropriate to reshape/ redesign this information section altogether.

**Comment by s-gbz** [comment]
Closed by 51484b917fadf60ad95f4f5950df87198b680627
