### ISSUE TITLE
Improve text box style

### ISSUE THREAD

**Issue by liam-k** [codeklasse/codeklasse.de#61]
Not strictly an inconsistency and of lower importance – but our way of presenting text and images could be a bit sleeker, like one of the three original designs I made in Sketch. 

![codeklasse landing 10-Jan-22(1)](https://user-images.githubusercontent.com/34057943/171489830-4019ee7a-65a2-49df-acbc-5d52b4d02010.png)

**Comment by s-gbz** [comment]
![image](https://user-images.githubusercontent.com/23424538/171377739-f1641e25-a098-4922-b82c-92ce521f4895.png)
Would you mind posting a screenshot so I can get to work on it @liam-k ?
Thanks!

(I'd be great if you'd rather paste screenshots than link files in future. Makes the information more accessible and serves an archive-ish function at the same time)

**Comment by s-gbz** [comment]
Thanks! I wouldn't even have known where to start looking for the file and well haha, you're actually right. I thought there was more to take from the Sketch, but I actually think the current implementation is superior.
Well, thanks anyways I'll see what I can take from it :+1:

**Comment by s-gbz** [comment]
Closed by 51484b917fadf60ad95f4f5950df87198b680627
